# action.yml
name: 'Advance Security Kenna Action'
description: 'GitHub Advance Security Action to push SARIF files into Kenna'
author: GeekMasher

inputs:
  endpoint:
    description: 'Kenna Endpoint'   
    required: true
  token:
    description: 'Kenna Access Token'
    required: true
  connector:
    description: 'Kenna API Connector'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -e ${{ inputs.endpoint }}
    - -t ${{ inputs.token }}
    - -c ${{ inputs.connector }}
